// Code generated by cmd/reset. DO NOT EDIT.

package resetpkg

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}

	rs.I = 0
	rs.Str = ""
	if rs.StrP != nil {
		*rs.StrP = ""
	}
	rs.S = rs.S[:0]
	clear(rs.M)
	if rs.Child != nil {
		rs.Child.Reset()
	}
}
