package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"sort"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

var analyzer = &analysis.Analyzer{
	Name:     "reset",
	Doc:      "generates Reset() methods for structs with // generate:reset comment",
	Run:      run,
	Requires: []*analysis.Analyzer{inspect.Analyzer},
}

func run(pass *analysis.Pass) (interface{}, error) {
	inspectResult := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	fileToCommentMap := make(map[*ast.File]ast.CommentMap)
	var pkgDir string
	for _, file := range pass.Files {
		fname := pass.Fset.File(file.Pos()).Name()
		if filepath.Base(fname) == "reset.gen.go" {
			continue
		}
		if pkgDir == "" {
			pkgDir = filepath.Dir(fname)
		}
		fileToCommentMap[file] = ast.NewCommentMap(pass.Fset, file, file.Comments)
	}

	var allStructs []*structInfo
	inspectResult.Nodes([]ast.Node{(*ast.GenDecl)(nil)}, func(n ast.Node, push bool) bool {
		if !push {
			return true
		}
		g := n.(*ast.GenDecl)
		if g.Tok != token.TYPE {
			return true
		}
		file := fileContaining(pass, g.Pos())
		if file == nil {
			return true
		}
		cmap, ok := fileToCommentMap[file]
		if !ok {
			return true
		}
		if !hasGenerateReset(cmap[g]) {
			return true
		}
		allStructs = append(allStructs, structInfosFromGenDecl(g, file)...)
		return true
	})

	if len(allStructs) == 0 {
		return nil, nil
	}

	sort.Slice(allStructs, func(i, j int) bool { return allStructs[i].name < allStructs[j].name })

	resetterTypes := make(map[string]bool)
	for _, s := range allStructs {
		resetterTypes[s.name] = true
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pass.Pkg.Name() + "\n\n")

	for _, s := range allStructs {
		body := generateResetBody(s, resetterTypes)
		buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n\tif %s == nil {\n\t\treturn\n\t}\n\n%s}\n\n",
			s.receiver, s.name, s.receiver, body))
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, nil
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "reset.gen.go"), formatted, 0644); err != nil {
		return nil, nil
	}
	return nil, nil
}
