// Генерирует Reset() для структур с // generate:reset. Запуск: go run ./cmd/reset ./...
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/analysis/singlechecker"
	"golang.org/x/tools/go/ast/inspector"
)

const generateComment = "generate:reset"

var analyzer = &analysis.Analyzer{
	Name:     "reset",
	Doc:      "generates Reset() methods for structs with // generate:reset comment",
	Run:      run,
	Requires: []*analysis.Analyzer{inspect.Analyzer},
}

func main() {
	singlechecker.Main(analyzer)
}

func run(pass *analysis.Pass) (interface{}, error) {
	inspectResult := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	fileToCommentMap := make(map[*ast.File]ast.CommentMap)
	var pkgDir string
	for _, file := range pass.Files {
		fname := pass.Fset.File(file.Pos()).Name()
		if filepath.Base(fname) == "reset.gen.go" {
			continue
		}
		if pkgDir == "" {
			pkgDir = filepath.Dir(fname)
		}
		fileToCommentMap[file] = ast.NewCommentMap(pass.Fset, file, file.Comments)
	}

	var allStructs []*structInfo
	inspectResult.Nodes([]ast.Node{(*ast.GenDecl)(nil)}, func(n ast.Node, push bool) bool {
		if !push {
			return true
		}
		g := n.(*ast.GenDecl)
		if g.Tok != token.TYPE {
			return true
		}
		file := fileContaining(pass, g.Pos())
		if file == nil {
			return true
		}
		cmap, ok := fileToCommentMap[file]
		if !ok {
			return true
		}
		if !hasGenerateReset(cmap[g]) {
			return true
		}
		allStructs = append(allStructs, structInfosFromGenDecl(g, file)...)
		return true
	})

	if len(allStructs) == 0 {
		return nil, nil
	}

	sort.Slice(allStructs, func(i, j int) bool { return allStructs[i].name < allStructs[j].name })

	resetterTypes := make(map[string]bool)
	for _, s := range allStructs {
		resetterTypes[s.name] = true
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pass.Pkg.Name() + "\n\n")

	for _, s := range allStructs {
		body := generateResetBody(s, resetterTypes)
		buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n\tif %s == nil {\n\t\treturn\n\t}\n\n%s}\n\n",
			s.receiver, s.name, s.receiver, body))
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, nil
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "reset.gen.go"), formatted, 0644); err != nil {
		return nil, nil
	}
	return nil, nil
}

type structInfo struct {
	pkgName  string
	name     string
	receiver string
	fields   []fieldInfo
}

type fieldInfo struct {
	name string
	typ  ast.Expr
}

func fileContaining(pass *analysis.Pass, pos token.Pos) *ast.File {
	for _, f := range pass.Files {
		if f.Pos() <= pos && pos <= f.End() {
			return f
		}
	}
	return nil
}

func structInfosFromGenDecl(g *ast.GenDecl, file *ast.File) []*structInfo {
	var result []*structInfo
	for _, spec := range g.Specs {
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}
		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			continue
		}
		name := typeSpec.Name.Name
		receiver := receiverName(name)
		var fields []fieldInfo
		for _, f := range structType.Fields.List {
			fieldName := typeExprName(f.Type)
			for _, n := range f.Names {
				fields = append(fields, fieldInfo{name: n.Name, typ: f.Type})
			}
			if len(f.Names) == 0 {
				fields = append(fields, fieldInfo{name: fieldName, typ: f.Type})
			}
		}
		result = append(result, &structInfo{
			pkgName:  file.Name.Name,
			name:     name,
			receiver: receiver,
			fields:   fields,
		})
	}
	return result
}

func hasGenerateReset(comments []*ast.CommentGroup) bool {
	for _, cg := range comments {
		for _, c := range cg.List {
			if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == generateComment {
				return true
			}
		}
	}
	return false
}

func receiverName(typeName string) string {
	if typeName == "" {
		return "r"
	}
	var b strings.Builder
	for i, r := range typeName {
		if i == 0 {
			if r >= 'A' && r <= 'Z' {
				b.WriteRune(r - 'A' + 'a')
			} else if r >= 'a' && r <= 'z' {
				b.WriteRune(r)
			}
			continue
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r - 'A' + 'a')
			break
		}
	}
	if b.Len() == 0 {
		return "r"
	}
	return b.String()
}

func typeExprName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return typeExprName(t.X)
	case *ast.SelectorExpr:
		return typeExprName(t.Sel)
	case *ast.ArrayType:
		return ""
	default:
		return ""
	}
}

func generateResetBody(s *structInfo, resetterTypes map[string]bool) string {
	var lines []string
	for _, f := range s.fields {
		line := generateResetLine(s.receiver, f.name, f.typ, resetterTypes)
		if line != "" {
			lines = append(lines, "\t"+line)
		}
	}
	return strings.Join(lines, "\n") + "\n"
}

func generateResetLine(receiver, fieldName string, typ ast.Expr, resetterTypes map[string]bool) string {
	base := receiver + "." + fieldName

	switch t := typ.(type) {
	case *ast.Ident:
		name := t.Name
		if zero, ok := zeroValueForBasic(name); ok {
			return base + " = " + zero
		}
		if resetterTypes[name] {
			return fmt.Sprintf("if r, ok := interface{}(&%s).(interface{ Reset() }); ok {\n\t\tr.Reset()\n\t}", base)
		}
		return ""
	case *ast.StarExpr:
		inner := t.X
		switch inner := inner.(type) {
		case *ast.Ident:
			name := inner.Name
			if zero, ok := zeroValueForBasic(name); ok {
				return fmt.Sprintf("if %s != nil {\n\t\t*%s = %s\n\t}", base, base, zero)
			}
			if resetterTypes[name] {
				return fmt.Sprintf("if %s != nil {\n\t\t%s.Reset()\n\t}", base, base)
			}
			return fmt.Sprintf("if %s != nil {\n\t\tif r, ok := interface{}(%s).(interface{ Reset() }); ok {\n\t\t\tr.Reset()\n\t\t}\n\t}", base, base)
		case *ast.ArrayType:
			return fmt.Sprintf("if %s != nil {\n\t\t*%s = (*%s)[:0]\n\t}", base, base, base)
		case *ast.MapType:
			return fmt.Sprintf("if %s != nil {\n\t\tclear(*%s)\n\t}", base, base)
		case *ast.SelectorExpr:
			return fmt.Sprintf("if %s != nil {\n\t\tif r, ok := interface{}(%s).(interface{ Reset() }); ok {\n\t\t\tr.Reset()\n\t\t}\n\t}", base, base)
		default:
			return fmt.Sprintf("if %s != nil {\n\t\tif r, ok := interface{}(%s).(interface{ Reset() }); ok {\n\t\t\tr.Reset()\n\t\t}\n\t}", base, base)
		}
	case *ast.ArrayType:
		if t.Len == nil {
			return base + " = " + base + "[:0]"
		}
		return ""
	case *ast.MapType:
		return "clear(" + base + ")"
	case *ast.SelectorExpr:
		return fmt.Sprintf("if r, ok := interface{}(&%s).(interface{ Reset() }); ok {\n\t\tr.Reset()\n\t}", base)
	default:
		return ""
	}
}

func zeroValueForBasic(name string) (string, bool) {
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune":
		return "0", true
	case "float32", "float64":
		return "0", true
	case "complex64", "complex128":
		return "0", true
	default:
		return "", false
	}
}
